version: "3.7"

x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  dv.twitch.viewer:
    image: dv.twitch.viewer:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        INSTALL_DEV: "true"
    volumes:
      - ../src:/workspace/
    env_file:
      - ../docker/.dev.env

networks:
  default:
    external:
      name: $NETWORK_NAME
